@startuml

' Sequence Diagram: User Authentication
actor User
participant ":Frontend" as App
participant ":User" as UserClass
participant ":UserDB" as UserDB
participant "Google Authentication API" as Google

activate User
User -> App: Click on Login
activate App
App->UserClass: Request Authentication
activate UserClass
UserClass -> UserDB: Request token
activate UserDB
UserDB -> UserClass: Return token
deactivate UserDB
UserClass -> Google: authenticateUser(token)
activate Google
alt Authentication Successful
    Google -> UserClass: Return Success
    deactivate Google
    UserClass -> App: Return Success
    App -> User: Grant access
else Authentication Failed
    UserClass -> App: Throw error
    deactivate UserClass
    App -> User: Show error message
end

@enduml
